server:
  port: 8082
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/springboot
    #url: r2dbc:tc:postgresql://springboot?TC_IMAGE_TAG=9.6.8&TC_INITSCRIPT=/initDatabase.sql
    username: springboot
    password: secret